finish up manifests

diff --git a/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/deployment.yaml b/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/deployment.yaml
--- a/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/deployment.yaml
+++ b/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/deployment.yaml
@@ -27,15 +27,16 @@ spec:
         - name: download-files
           image: registry.redhat.io/ubi9/httpd-24:9.7
           imagePullPolicy: IfNotPresent
-          command: 
+          command:
           - sh
           - -c
           - |
-            for i in kubeconfig kubeadmin-paassword agent.x86_64-rootfs.img; do
+            set -e
+            for i in kubeconfig kubeadmin-password agent.x86_64-rootfs.img; do
                 echo "Downloading $i..."
                 curl --fail --retry 10 --retry-all-errors --retry-delay 3 \
                      --output /pubsrv/"$i" \
-                     http://install-resources.svc.cluster.local:8080/pubsrv/"$i";
+                     http://install-resources.network-install.svc.cluster.local:8080/pubsrv/"$i" || { echo "Failed to download $i"; exit 1; }
             done
             echo "All files downloaded successfully."
           volumeMounts:
diff --git a/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/statefulset.yaml b/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/statefulset.yaml
--- a/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/statefulset.yaml
+++ b/images/bootstrap/overlay/etc/microshift/manifests.d/network-install/manifests/statefulset.yaml
@@ -26,6 +26,11 @@ spec:
       terminationGracePeriodSeconds: 10
       serviceAccountName: tftp-sa
       hostNetwork: true
+      dnsPolicy: ClusterFirstWithHostNet
+      hostAliases:
+      - ip: "192.168.100.1"
+        hostnames:
+        - "resources-network-install.apps.bootstrap.BASE_DNS_ZONE"
       initContainers:
         - name: download-files
           image: registry.redhat.io/ubi9/httpd-24:9.7
@@ -34,11 +39,12 @@ spec:
           - sh
           - -c
           - |
+            set -e 
             for i in grub.cfg grubx64.efi shimx64.efi agent.x86_64-initrd.img agent.x86_64-vmlinuz; do
                 echo "Downloading $i..."
                 curl --fail --retry 10 --retry-all-errors --retry-delay 3 \
                      --output /tftpboot/"$i" \
-                     http://install-resources.svc.cluster.local:8080/tftpboot/"$i";
+                     http://resources-network-install.apps.bootstrap.BASE_DNS_ZONE/tftpboot/"$i" || { echo "Failed to download $i"; exit 1; }
             done
             echo "All files downloaded successfully."
           volumeMounts:
@@ -77,7 +83,18 @@ spec:
     matchLabels:
       app.kubernetes.io/name: generate-install-media
       app.kubernetes.io/component: generate-install-media
+  template:
+    metadata:
+      labels:
+        app.kubernetes.io/name: generate-install-media
+        app.kubernetes.io/version: "1.0.0"
+        app.kubernetes.io/component: generate-install-media
+        app.kubernetes.io/part-of: bootstrap
     spec:
+      hostAliases:
+      - ip: "192.168.100.1"
+        hostnames:
+        - "registry-registry.apps.bootstrap.BASE_DNS_ZONE"
       terminationGracePeriodSeconds: 10
       serviceAccountName: ansible-runner
       securityContext:
